/*export { Triangle2 } from './Triangle2.js';
export { Immeuble } from './Immeuble.js';
export { Triangle } from './Triangle.js';
export { Planete } from './Planete.js';
export { Smiley } from './Smiley.js';*/
export { Route } from './Route.js';
export { Eau } from './Eau.js';
export { Poisson } from './Poisson.js';
export { Homme } from './Homme.js';
export { Montagne } from './Montagne.js';
export { Maison } from './Maison.js';
export { Voiture } from './Voiture.js';